#ifndef __mainframe__
#define __mainframe__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MyFrame1 */
class MainFrame : public MyFrame1
{
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __mainframe__
